### ISSUE TITLE
Diferent import statement

### ISSUE THREAD

**Issue by Migueacalle98** [EdisonJpp/react-export-table-to-excel#1]
I am using next.js v12 with type script but instead of using :
`import { useDownloadExcel } from "react-export-table-to-excel;`
I have to say:
`import { useDownloadExcel } from "react-export-table-to-excel/src";`

I am doing something wrong ?

**Comment by ppldheeraj** [comment]
is it working for you ?, for me it's saying can't resolve

**Comment by Ferced** [comment]
same here, I can't import it

**Comment by brianwachira** [comment]
me too
I am getting this error

![Screenshot from 2022-03-24 09-35-15](https://user-images.githubusercontent.com/28436092/159856900-06f5c251-3c57-4624-b438-5fc85199c108.png)

Does anyone know a solution?

**Comment by Gabriel-Vianna** [comment]
Not working for me too
![image](https://user-images.githubusercontent.com/36870716/160475891-086263f4-e988-42d1-9f4c-cddefe26690a.png)

**Comment by danvk** [comment]
The issue is that this library is distributed incorrectly on npm. The package includes only the TypeScript sources: https://yarnpkg.com/?q=react-export-table-to-excel&files

Instead, it should include the results of running these through `tsc`, namely `.js` and `.d.ts` files. This lets both JS and TS users import this library.

The best fix is for @EdisonJpp to release a new version with those files, but the workaround for now, assuming you're already using TypeScript, is is just to put the contents of this repo (the `src` dir) in your own project and import from that.

**Comment by EdisonJpp** [comment]
Cheers,

in version 1.0.6 this error was fixed;

We add another method that is used to export the excel only sending the header and body.

we add usage examples in both next.js and react.js

samples;
React.js: https://codesandbox.io/s/react-export-table-to-excel-sample-dvzkms
Next.js: https://codesandbox.io/s/react-export-table-to-excel-next-js-yzl74q

you can check in the repository ([repo](https://github.com/EdisonJpp/react-export-table-to-excel) )
